from .async_client import (
    async_fetch_page_text,
    async_fetch_page_text_with_fallback,
    async_fetch_paginated_soups,
    fetch_paginated_soups,
    fetch_paginated_soups_threaded,
)
from .client import (
    apply_response_encoding,
    create_session,
    fetch_html,
    fetch_html_by_curl,
    fetch_html_plain_insecure,
    fetch_json_data,
    fetch_response,
    get_effective_timeout,
    get_thread_session,
    remember_ssl_verify_failure,
    set_retry_timeout_extra_seconds,
    should_fallback_ssl,
    should_skip_ssl_verify,
)

__all__ = [
    "apply_response_encoding",
    "async_fetch_page_text",
    "async_fetch_page_text_with_fallback",
    "async_fetch_paginated_soups",
    "create_session",
    "fetch_html",
    "fetch_html_by_curl",
    "fetch_html_plain_insecure",
    "fetch_json_data",
    "fetch_paginated_soups",
    "fetch_paginated_soups_threaded",
    "fetch_response",
    "get_effective_timeout",
    "get_thread_session",
    "remember_ssl_verify_failure",
    "set_retry_timeout_extra_seconds",
    "should_fallback_ssl",
    "should_skip_ssl_verify",
]
